### ISSUE TITLE
Configure the logging level based on a string

### ISSUE THREAD

**Issue by nuest** [zatonovo/futile.logger#20]
I want to configure the logging level based on strings, e.g. `"WARN"`, but `flog.threshold(..)` only accepts the numbers that are accessible via the global constants such as `futile.logger::TRACE`. I wrote the following small helper function, but I'm sure you could also easily change `flog.threshold` to accept string values in the same way.

```{r}
getLoglevelForName <- function(x) {
    name <- tolower(x)
    
    level <- switch(x, "trace" = futile.logger::TRACE,
                    "debug" = futile.logger::DEBUG,
                    "warn" = futile.logger::WARN,
                    "info" = futile.logger::INFO,
                    "error" = futile.logger::ERROR,
                    "fatal" = futile.logger::FATAL)
    if(is.null(level))
        return(futile.logger::INFO)
    return(level)
}
```

Am I missing a way that this is aready possible?

Would you accept a pull request adding this feature to `flog.threshold`?

**Comment by muxspace** [comment]
This is integrated into 1.4 and is going on CRAN today. Thanks again for your contributions!
