### ISSUE TITLE
Appender that writes to syslog

### ISSUE THREAD

**Issue by asieira** [zatonovo/futile.logger#28]
It would be really useful if the package provided a default appender that submits logs to the local syslog process (if it exists) in a Mac OS X or *nix machine. :)

**Comment by muxspace** [comment]
Great idea! You're welcome to submit a pull request if you figure out how to do it.

**Comment by asieira** [comment]
The obvious path would be to develop R bindings to the `syslog.h` functions like Python did with this module: https://docs.python.org/2/library/syslog.html

The only question is if this should be on `futile.logger`, or if it instead should belong on a separate package (`syslogR`?) which could then be used to write a new appender. What do you think?

**Comment by muxspace** [comment]
I guess it depends on how complicated the binding is. If it's relatively small and has minimal dependencies, it would probably be most convenient to include it in this package. If you have a larger vision for it, then it'd be better to make it independent.

**Comment by asieira** [comment]
Shouldn't be too complicated for an experienced R package developer. Which I am not. :)

Also, since any C code that uses `syslog.h` will not work under Windows, won't this create problems for futile.logger on CRAN?

**Comment by nuest** [comment]
I don't see why you could not add a switch to only provide this feature on Linux. [Platform](https://www.r-bloggers.com/identifying-the-os-from-r/) [detection](https://stackoverflow.com/questions/4747715/how-to-check-the-os-within-r) is just a few lines of code.

The (now apparently stale?) project `timber` did integrate `syslog.h`, could be reused?
https://github.com/mrcsparker/timber

So, just want to give this feature a :+1: though I cannot work on it.

**Comment by atheriel** [comment]
This should now be possible due to the new [`rsyslog`](https://cran.r-project.org/package=rsyslog) package:

```r
#' @param identifier A string identifying the application.
#' @param ... Further arguments passed on to \code{\link[rsyslog]{open_syslog}}.
appender.syslog <- function(identifier, ...) {
  if (!requireNamespace("rsyslog", quietly = TRUE)) {
    stop("appender.syslog requires the 'rsyslog' package.", call. = FALSE)
  }
  rsyslog::open_syslog(identifier = identifier, ...)

  function(line) {
    rsyslog::syslog(line, level = "INFO") 
  }
}
```

I'll try to put together a PR.
