### ISSUE TITLE
Suggested optimisation of flog.namespace()

### ISSUE THREAD

**Issue by bhmevik** [zatonovo/futile.logger#37]
I noticed that most of the time in flog.trace() etal is spent in flog.namespace().  For instance:
## Testing the logger functions directly:

flog.threshold(INFO)
## Default:

Rprof(line.profiling = TRUE)
for (i in 1:20000) { flog.trace("A message") }
Rprof(NULL)
summaryRprof(lines = "both")            # 28.58 seconds
## Avoiding flog.namespace():

Rprof(line.profiling = TRUE)
for (i in 1:20000) { flog.trace("A message", name = 'ROOT') }
Rprof(NULL)
summaryRprof(lines = "both")            #  3.98 seconds

So 80-90 % of the time is spent in getting the name of the name space.  Profiling flog.namespace() directly, indicated that it is in capture.output() and/or str() the time is spent. Looking into the code of str(), I saw that for environments, it basically does format(), so I tested with an alternative way of getting the string representation of the environment, i.e. instead of

  s <- capture.output(str(topenv(environment(sys.function(where))), give.attr=FALSE))

I tried

  s <- format(topenv(environment(sys.function(where))))

Profiling showed that the alternative implementation of flog.namespace() is much faster:
## Testing flog.namespace() directly:

Rprof(line.profiling = TRUE)
for (i in 1:20000) { tmp <- flog.namespace() }
Rprof(NULL)
summaryRprof(lines = "both")            #  14.82 seconds
## Alternative flog.namespace() directly:

Rprof(line.profiling = TRUE)
for (i in 1:20000) { tmp <- flog.namespace2() }
Rprof(NULL)
summaryRprof(lines = "both")            #  3.32 seconds

And when using the alternative flog.namespace() in flog.trace(), it ran about twice as fast as before:
## With alternative flog.namespace():

Rprof(line.profiling = TRUE)
for (i in 1:20000) { flog.trace2("A message") }
Rprof(NULL)
summaryRprof(lines = "both")            #  17.14 seconds.

My understanding of environments etc is not perfect, so I cannot guarantee that the alternative will work in all cases, but at least it seems to work for the cases I've tested.

The reason for suggesting the optimisation is that I tend to put a lot of trace messages in my code while developing it, and then increase the log level when actually using the code.  Therefore I don't want too much overhead of logging calls, at least not when they don't print anything. (I had a case where 97 % of the time was spent inside flog.trace() when the threshold was INFO.)

**Comment by bhmevik** [comment]
I forgot to mention that the package at leastl passes its test suite with my suggested modification.

**Comment by kenahoo** [comment]
@bhmevik , could you code up a pull request to go with this, to see your suggested optimization directly?

**Comment by bhmevik** [comment]
Ok, I've finally had time to do it now.
