### ISSUE TITLE
Feature: Intercept warning() function ( with flog.warn() )

### ISSUE THREAD

**Issue by hardingnj** [zatonovo/futile.logger#5]
Firstly, thanks for this great package- I'm a big user, it has met a real need for me!

I was wondering if you'd consider intercepting warning() statements with futile.logger? From email you suggested it would be hard as warning is low-level, but would be a great addition.

**Comment by aryoda** [comment]
I have implemented a package `tryCatchLog` (see https://github.com/aryoda/tryCatchLog) which offers similar (and more) functionalities. It uses `futile.logger`. Perhaps it is a good idea to separate logging and error handling into two different packages.
