### ISSUE TITLE
Logging layout

### ISSUE THREAD

**Issue by pintuaitha** [zatonovo/futile.logger#50]
Hi Zatonovo,
I implemented python style logging in R using futile.logger. My log prints like below but i need some layout change on the logging 
DEBUG[yyyy-mm-dd hh:mm:ss] message..
Will i be able to change the format to print the date first using futile.logger
[yyyy-mm-dd hh:mm:ss]DEBUG:Message
[https://gist.github.com/jonathancallahan/a03b9ee7c1817d74803447856c64e518](url)

**Comment by muxspace** [comment]
Yes, just create a custom formatter
