### ISSUE TITLE
Use futile.logger in package

### ISSUE THREAD

**Issue by instantkaffee** [zatonovo/futile.logger#57]
This is not really an issue, rather than question how to apply futile.logger as R package author:

I am looking for some references teaching me how to embed futile.logger functionality into an R package. 

Use case:
The R package will provide funtions to the user.
The user of the package shall be able to define the file location and threshold of logging.

Thx for some helpful pointers.

**Comment by skamkar** [comment]
you leverage .onLoad, most folks (hadley included) put this in zzz.R, e.g.:

.onLoad <- function(libname, pkgname){
  futile.logger::flog.layout(layout.format("[~l] [~t] [~n.~f] ~m"), name=pkgname)
  futile.logger::flog.threshold(futile.logger::INFO, name=pkgname)
}

then, routines inside your package _mypackage_ can call:

futile.logger::flog.error("the sky, it be falling", name="_mypackage_")

note, .onLoad needs to keep pkgname as general, but when it loads, it will have created a logger object, mapped to the name of your actual packge

**Comment by muxspace** [comment]
Quite right. Also, any users of your package can override the logging threshold by making their own call to `flog.threshold`, such as `futile.logger::flog.threshold(futile.logger::DEBUG, name=pkgname)`.

**Comment by jsonbecker** [comment]
Sorry I'm also attempting to do this and I'm not quite following the solution. My main desire is to set all the logging that my package functions do to a file appender when running tests. I don't want to have to write any additional code within each call to a log (like specifying the name.. that seems excessive to me). Adding an `.onLoad` function with `futile.logger::flog.appender(appender.file())` etc didn't seem to do it.
