### ISSUE TITLE
Feature: printing of current function call

### ISSUE THREAD

**Issue by hardingnj** [zatonovo/futile.logger#6]
Hi,

I often find myself writing code to catch the name of the executing function, e.g.:

```
flog.debug('made it past input checks in %s', as.character(match.call()[[1]]));
```

Would it be possible to have a shortcut to this, so perhaps something like:

```
flog.debug('Value of x in %f is %s', x)
```

**Comment by aryoda** [comment]
Just to let you know:

If have implemented a package names `tryCatchLog` that is based on `futile.logger` which prints the full call stack for errors and warnings: https://github.com/aryoda/tryCatchLog

It also has also similar (and more) functionalities like your `ftry` function.
