### ISSUE TITLE
increment version number?

### ISSUE THREAD

**Issue by r2evans** [zatonovo/futile.logger#62]
Might I suggest that you increment the version in `DESCRIPTION`?

```diff
 Package: futile.logger
 Type: Package
 Title: A Logging Utility for R
-Version: 1.4.3
+Version: 1.4.3.9000
 Date: 2016-07-10
 Author: Brian Lee Yung Rowe
 Maintainer: Brian Lee Yung Rowe <r@zatonovo.com>
```

I recently looked in your code and found functionality I was hoping to find (a PR you merged into `layout.json`). When I noticed that this version and the one on CRAN were the same, I installed from CRAN ... but lo-and-behold, it wasn't there.

My use of `.9000` is a convention I've seen that indicates a development version, saving `1.4.4` for the next release to CRAN. Something that distinguishes it from the CRAN version is the important part.

Thank you!

**Comment by muxspace** [comment]
Thanks for pointing this out. In the past I haven't incremented version number until I push to CRAN, but it does make sense to increment beforehand. I'll increment to 1.4.4 and push this week.

**Comment by r2evans** [comment]
Some other developers adopt a different tactic that keeps the version numbers distinct. If a version number is simply three digits (1.4.3), then it is a released stable version. If a system has a fourth dotted number (1.4.3.9000), then it was installed from GitHub. It means that when you are nearing release on CRAN, you change the version, send to CRAN, then change the version again.

Two advantages are (1) that it's immediately evident that I have a dev version installed, and (2) it is unambiguous that what I have installed is newer than what is currently on CRAN, and is inferior to the version you release next. As long as I install from GitHub, I'll always be numerically between the CRAN release version numbers.

I have seen the use of incrementing fourth numbers (1.4.3.1001, then 1.4.3.1002, etc), and though this seems to have even better differentiation on versions installed, it's a bit more work than I think necessary. (It also reminds me a little of subversion versioning, and I was never really happy/comfortable with `svn` :-)
