### ISSUE TITLE
Semantics of ftry and try are different (warnings should not stop further evaluation of the expression param)

### ISSUE THREAD

**Issue by aryoda** [zatonovo/futile.logger#67]
If a warning occurs in `ftry` the evaluation of the expression is stopped due to establishing a warning handler in `tryCatch` (handled conditions in `tryCatch` do always stop the further evaluation).

`try` of base R behaves differently.

Proposal: Fix or document different semantics...

Example:
```
library(futile.logger)
sessionInfo()  # futile.logger_1.4.3

ftry({
       log(-1)   # throws a warning ("NaNs produced")
       print("warnings should not stop evaluation of this expression")
})
# WARN [2017-12-26 10:01:09] NaNs produced



# Compare:
try({
  log(-1)   # throws a warning ("NaNs produced")
  print("warnings should not stop evaluation of this expression")
})
# [1] "warnings should not stop evaluation of this expression"
# Warning message:
# In log(-1) : NaNs produced
```

The solution would establish a warning handler using `withCallingHandlers` within `tryCatch`...

**Comment by muxspace** [comment]
Thanks for pointing this out. I'll look into making the two behaviors consistent.

**Comment by mtmorgan** [comment]
`w.handler` in `ftry` should be implemented as
```
w.handler <- function(e) {
    flog.warn("%s", e)
    invokeRestart("muffleWarning")
}
```

**Comment by joeHickson** [comment]
with calling handlers might be the answer - it triggers the handler in situ rather than breaking the stack back up to the error handler. This is also handy if you want the actual stack trace of the error
e.g.

```R
warning_handler <- function(w){...}
error_handler <- function(e){...}
tryCatch(
  withCallingHandlers(
     some_func,
     warning = warning_handler ,
     error = function(e) {
            futile.logger::flog.error(capture.output(rlang::trace_back()))
          }
  ),
  error = error_handler 
)
```
