### ISSUE TITLE
Dates don't print correctly

### ISSUE THREAD

**Issue by ysgit** [zatonovo/futile.logger#68]
I'm pretty sure the use of `c(msg, parsed)` here strings the arguments of their classes so for instance dates are printed as their integer value.

https://github.com/zatonovo/futile.logger/blob/852fc6736de07f4b7a0e5a96292f3038d4e8006c/R/layout.R#L119

I'm not an R expert but maybe this could be resolved by using `c(list(msg), parsed)`

**Comment by iwccsbfb** [comment]
Hi @ysgit , it shall not be a problem:
```
> library(futile.logger)
> flog.info(Sys.Date())
INFO [2017-12-27 11:35:02] 2017-12-27
> flog.info( c(Sys.Date(), Sys.Date()) )
INFO [2017-12-27 11:35:30] 2017-12-27
INFO [2017-12-27 11:35:30] 2017-12-27
> flog.info('%s', Sys.Date())
INFO [2017-12-27 11:36:16] 2017-12-27
> flog.info('%s', c(Sys.Date(), Sys.Date())
+ )
INFO [2017-12-27 11:36:25] 2017-12-27
INFO [2017-12-27 11:36:25] 2017-12-27
> flog.info('%s %s', Sys.Date(), 1)
INFO [2017-12-27 11:36:33] 2017-12-27 1
```

**Comment by ysgit** [comment]
This is what I get

```r
> date <- Sys.Date()
> futile.logger::flog.info("Today is %s", date)
INFO [2017-12-27 19:58:25] Today is 17527
```

**Comment by iwccsbfb** [comment]
@ysgit PR #54 shall already fixed this bug. Please try with latest version of futile.logger by running:

**Comment by ysgit** [comment]
It works, thanks. Any idea when the CRAN version will be updated?

**Comment by muxspace** [comment]
I plan on pushing some updates in February. The CRAN release schedule is usually once or twice a year, unless there's something critical.

**Comment by aryoda** [comment]
@muxspace Please publish a new version at CRAN (the CRAN version is still from 2016!). THX :-)
