### ISSUE TITLE
Logger name in the message

### ISSUE THREAD

**Issue by kota7** [zatonovo/futile.logger#69]
I think it would be great if the message includes the logger name, like

```r
> library(futile.logger)
> flog.info("foo", name="mylogger")
INFO | mylogger | 2018-01-11 17:41:13 : foo
```

At the beginning, I thought custom layout with "~n" (namespace) and "~f" (function) provides good information about where the logs come from, but when functions are nested, mere function names are not very helpful.

If this is already supported, please kindly let me know.

**Comment by muxspace** [comment]
Thanks, I merged your PR
