### ISSUE TITLE
futile.logger & concurrent shiny sessions

### ISSUE THREAD

**Issue by paulvanoppen** [zatonovo/futile.logger#71]
We are using futile.logger in an R shiny application.
The logger writes user error messages from the application to a log file in the root directory of the application on our R server (linux).
As Shiny allows for multiple sessions to run concurrently we have a concern: if two application sessions would be writing to the same log file at the same time, would futile.logger handle this correctly? Or would the second session, that finds an open log file while trying to write, generate an error message?

We use the function flog.info to write to the log file.

Thanks.

**Comment by muxspace** [comment]
Hi, I'm not all that familiar with how shiny applications work. But R is single-threaded, and futile.logger generally appends to files, so I assume it should work. Probably easiest to try a quick experiment to verify the behavior.

**Comment by paulvanoppen** [comment]
So far so good. We are running futile.logger on our Linux R shiny server and have not seen any write conflicts.

**Comment by muxspace** [comment]
Great to hear!

**Comment by him4u324** [comment]
Can you help on how to use futile.logger in Shiny application. Thanks

**Comment by paulvanoppen** [comment]
We use standard futile.logger functions to write error messages to a log file we keep in the project root on the shiny server. We have defined an appender function which writes to that log file. As soon as we call flog.info, which is done when an error is handled in our shiny app, an error message is appended to the log file. 
There is really nothing special about using futile.logger in shiny. Make sure that the application has write access to the log file.
