### ISSUE TITLE
Log data frame to file and console

### ISSUE THREAD

**Issue by petobens** [zatonovo/futile.logger#76]
What's the best way to log a dataframe to a file? I found this question in [SO](https://stackoverflow.com/questions/16892770/r-data-frame-view-in-log-file) and tried doing something like
```R
    flog.logger(name = "logger", threshold = DEBUG,
                        appender = appender.tee(file.path(LOG_DIR, "transform.log")))
    flog.info(write.table(df, sep="\t"), name = "logger")
```
However I doesn't seem to do the trick. Thanks in advance

**Comment by aryoda** [comment]
I would create a separate CSV file (using `write.table` and write only the file name into the log.

Otherwise you wood flood your log file with data!

BTW: Are you sure your issue is in the right place (this is the `futile.logger` package, in your SO question you mentioned `log4r`)?

**Comment by muxspace** [comment]
Sorry for the late reply, but you can use the `capture` option of the logger functions.
e.g.
```
flog.info("A data frame", df, capture=TRUE)
```
That will print the object as-is on a new line. The message is required, but it can be an empty string.
