### ISSUE TITLE
SUGGESTION: Use message():s instead of cat() to stdout

### ISSUE THREAD

**Issue by HenrikBengtsson** [zatonovo/futile.logger#91]
When outputting to the terminal, it looks like futile.logger outputs to the standard output, e.g.

https://github.com/zatonovo/futile.logger/blob/9e65943e0f5ed68922ef842fb70854c07fb22176/R/appender.R#L108-L111

This causes log messages to be captured by for instance `capture.output()`, e.g.

```r
> library(futile.logger)
> flog.threshold(DEBUG, name="logger.a")
NULL

> capture.output(flog.debug("Hey there", name="logger.a"))
[1] "DEBUG [2020-02-09 11:24:31] Hey there"

> capture.output(flog.warn("woops", name="logger.a"))
[1] "WARN [2020-02-09 11:24:32] woops"
```

One problem with this is report generators/vignette engines.  By design and at their core, they capture stdout to include it in the vignette product.  I'd argue that in most use cases, we don't want this as the default behavior.

A related problem is what is mentioned in https://github.com/zatonovo/futile.logger/issues/84#issuecomment-446509018:

> You will see that the logs will be printed correctly (timings are OK), but they are only flushed at the end of the future.

# Suggestion

Produce futile console output via R's `message()` function.  This will (i) make future console output to be sent to the standard error (stderr) by default, and (ii) formally messages are conditions, which can be handled via condition handlers, e.g. `base::withCallingHandlers()`.

```sh
.outputToConsole <- function(line) {
  msg <- paste(line, collapse="")
  message(msg, appendLF = FALSE)
}

appender.console <- function() 
{ 
  function(line) .outputToConsole(line)
} 
```

With this, the behavior would become:
```sh
> capture.output(flog.debug("Hey there", name="logger.a"))
DEBUG [2020-02-09 11:24:31] Hey there
[1] ""

> capture.output(flog.warn("woops", name="logger.a"))
WARN [2020-02-09 11:24:32] woops
[1] ""
```

If you think there is a need for both the old and the new behavior, then that could be controlled by having `appender.console()` condition on an R option, e.g. `futile.logger.console` taking values in `c("stdout", "message")`.

Even better would be to use:

```sh
.outputToConsole <- function(line) {
  msg <- paste(line, collapse = "")
  cond <- simpleMessage(msg, appendLF = FALSE)
  class(cond) <- c("futile.logger.message", class(cond))
  message(cond)
}
```

That would make it possible to distinguish `futile.logger.message`:s from regular `message`:s.

There's one more minor, but important tweak to this, but I'll post it as a comment in another thread.

**Comment by muxspace** [comment]
Hi @HenrikBengtsson thanks for the suggestion. Seems fine to me, though I'm not sure what sort of downstream effects it might have. I think it's worth creating a branch and seeing if people want to test the change in functionality.

**Comment by HenrikBengtsson** [comment]
Sounds good.  One thing could be other tools expect the output on stdout and when using messages they end up on stderr.  That's why I think you might have to provide an R option `futile.logger.console`/env var `R_FUTURE_LOGGER_CONSOLE` to control this during a transition period and for backward compatible reasons.

**Comment by muxspace** [comment]
Well pandemic kind of slowed progress on this, but I incorporated your suggestions @HenrikBengtsson and pushed a new tag here 1.4.5. There's an environment variable `FUTILE_LOGGER_LEGACY` that defaults to `FALSE`, which can override the new behavior with the old behavior.

**Comment by aryoda** [comment]
@aryoda Reminder to myself to document this API-breaking change in v1.4.5 (semantics has changed, not signature!) in the `NEWS.md` since it affects eg. existing unit tests that use logging the check expectations (even though this is not the best way of implementing unit tests but sometimes the easist ;-)

Eg. in `testthat` `expect_output()` must be replaced with `expect_message()` now...

Also check that the roxygen doc is updated (and contains the `FUTILE_LOGGER_LEGACY` env var as hint)...
