### ISSUE TITLE
Please publish a new CRAN version ASAP (the current version is from 2016)

### ISSUE THREAD

**Issue by aryoda** [zatonovo/futile.logger#92]
There are so many new features missing in the current old CRAN version, eg.

`
flog.layout(layout.simple.parallel)     # Use a default format with a process id
`

This is eg. need when catching and logging conditions with `tryCatchLog`, see issue https://github.com/aryoda/tryCatchLog/issues/52#issuecomment-600288133

**Comment by muxspace** [comment]
Hi I've stopped publishing to CRAN. You can install the packages directly from github.

**Comment by aryoda** [comment]
THX for this info, what a pity!

Is there a special reason for that?

Could someone (eg. me) take over the responsibility for publishing at CRAN?

**Comment by muxspace** [comment]
I just haven't had time to maintain my R libraries past few years. If you want to publish to CRAN that would be great. Let's figure out what makes sense. I suppose we can see if  @HenrikBengtsson might know if anyone in the BioConductor world might be interested in helping out as well.

**Comment by muxspace** [comment]
I just haven't had time to maintain my R libraries past few years. If you want to publish to CRAN that would be great. Let's figure out what makes sense. I suppose we can see if  @HenrikBengtsson might know if anyone in the BioConductor world might be interested in helping out as well.
