### ISSUE TITLE
Inconsistency in string substitution errors

### ISSUE THREAD

**Issue by joeHickson** [zatonovo/futile.logger#94]
too many arguments is acceptable, too few throws an error.
```
> flog.warn("%s", 1, 2)
WARN [2020-09-02 11:55:18] 1
> flog.warn("%s %s", 1)
Error in (function (fmt, ...)  : too few arguments
ERROR [2020-09-02 11:55:35] aborting
```

I think this might just be exposing a quirk of an underlying library but I am unsure. Any suggestions?

**Comment by muxspace** [comment]
It's just using `sprintf` under the hood, so the behavior will be the same.
