### ISSUE TITLE
Enable testthat unit testing in RStudio (function "get_log_output" not found)

### ISSUE THREAD

**Issue by aryoda** [zatonovo/futile.logger#99]
# Problem description

If I clone `futile.logger`, build the package in RStudio and try to run the tests in RStudio via Build > Test package many unit tests fail because the testing helper function `get_log_output` is not found.

The same failures occur if I use `devtools::test()` instead.

```
> devtools::test()
Loading futile.logger
Testing futile.logger
✓ |  OK F W S | Context
x |   0 3     | debug level logging                                                                                                 
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Error (test_debug.R:6:5): debug level is logged
Error: could not find function "get_log_output"

Error (test_debug.R:12:5): higher levels are logged
Error: could not find function "get_log_output"

...

══ Results ═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
Duration: 0.1 s

[ FAIL 10 | WARN 0 | SKIP 0 | PASS 0 ]

```

# Problem analysis

This helper function is contained in the `tests/testthat.R` file and therefore not visible in the testthat unit tests.

The file is only uses I if I run the unit tests via the command line with `R CMD check futile.logger`.

# Proposed solution

The best practice to inject testing helper functions using `testthat` is to put the helper functions in the "tests/testthat" folder and use a file name starting with "helper-*.R" so that `testthat` will automatically load the helper function for each test file, eg.:

`tests/testthat/helper-log-output.R`

See: https://stackoverflow.com/a/41777777/

# Alternatives

Testing helper functions could also be put into the "R" folder of the package without exporting these functions.
This may "polute" the package functions (even though only internally) so the proposed solution does separate the testing helper functions more clear.

See also: https://cloud.r-project.org/web/packages/testthat/vignettes/custom-expectation.html

# Next steps

I will submit a pull request...

**Comment by muxspace** [comment]
Closing this since it's now merged
